//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Employee_Management_Project
{
    using System;
    using System.Collections.Generic;

    public partial class Employee
    {
        public int Id { get; set; }
        public string Emp_Name { get; set; }
        public string Emp_Designation { get; set; }
        public string Emp_Salary { get; set; }
        public string Emp_Address { get; set; }
        public string Emp_Email { get; set; }
        public string Emp_MobileNo { get; set; }
        public string Password { get; set; }

       

        public List<Employee> Employees { get; set; } = new List<Employee>();
    }
}
